### ISSUE TITLE
Syndicated Links Displaying to the Far Left

### ISSUE THREAD

**Issue by mrkrndvs** [pfefferle/ZenPress#10] opened 2017-12-17 11:02 UTC
I really like ZenPress, but have been wondering about the inclusion of Syndicated Links. They are presented in the far left. Is this intentional? Is it something in the [Syndication Links Plugin](https://github.com/dshanske/syndication-links)?

![screenshot 2017-12-17 at 9 58 52 pm](https://user-images.githubusercontent.com/13294754/34078828-b4898928-e375-11e7-8c0f-e9b33cfe361c.png)

**Comment by pfefferle** [comment] 2017-12-17 11:15
It is a theme problem, thanks for reporting, I will have a look!

**Comment by dshanske** [comment] 2017-12-17 16:58
Would you consider integrating support? You can unhook the content filter and call the display directly

**Comment by pfefferle** [comment] 2017-12-17 17:19
sure, but it should both work

**Comment by mrkrndvs** [comment] 2017-12-19 00:33
@pfefferle the strange formatting also occurs when you search for something 

![zenpress search](https://user-images.githubusercontent.com/13294754/34134686-4ceecd32-e4b0-11e7-99a3-24cff004ee67.png)

Assume that this is probably different, but I thought that I would add it here, just in case it is related.

**Comment by pfefferle** [comment] 2017-12-19 06:18
Do you use the latest master version?

**Comment by mrkrndvs** [comment] 2017-12-19 06:47
My previous version had been installed November 17. Just uploaded the latest Master. Both errors still there.

**Comment by pfefferle** [comment] 2017-12-19 07:26
Hmm, I will have a Look, I can’t reproduce it at my blog.

**Comment by pfefferle** [comment] 2017-12-19 07:28
Can you post the URL of the blog here?

**Comment by mrkrndvs** [comment] 2017-12-19 07:38
https://collect.readwriterespond.com/

**Comment by pfefferle** [comment] 2017-12-19 08:33
do you use any plugins that hooks into the post content? there is no `<p>` element around the paragraphs... that's why it shows up full size.

**Comment by pfefferle** [comment] 2017-12-19 08:37
Syndication Links Plugin is using a `span` element, so it can't be centered... I filed an issue there.

**Comment by mrkrndvs** [comment] 2017-12-19 10:01
Thank you

**Comment by pfefferle** [comment] 2018-02-12 21:05
@mrkrndvs I committed a native implementation of Syndication Links, I am curious about your thoughts.

![bildschirmfoto 2018-02-12 um 22 03 33](https://user-images.githubusercontent.com/2373/36119637-da7a65b0-1040-11e8-8668-f87a2a0ba49b.png)

**Comment by pfefferle** [comment] 2018-02-12 21:06
Ah, I saw you switched the theme... never mind ;)

**Closed by pfefferle** 2018-02-12 21:06 UTC

**Comment by mrkrndvs** [comment] 2018-02-13 11:58
Looks good @pfefferle. I notice that the search still has a SPAN issue?

![screenshot 2018-02-13 at 10 51 41 pm](https://user-images.githubusercontent.com/13294754/36148724-21406b7c-1111-11e8-9ff3-2f765d8b722f.png)

Also, I have collected some thoughts [here](https://collect.readwriterespond.com/zenpress/).

**Comment by pfefferle** [comment] 2018-02-13 12:27
@mrkrndvs do you use Gutenberg?

**Comment by pfefferle** [comment] 2018-02-13 12:31
I tried to optimize the plugin with Gutenberg, so that you will be able to use content that is wider than the normal content, like here: https://notiz.blog/2017/12/07/zwoelf/ or here: https://notiz.blog/2017/10/04/readability/

But that means, that you always have to have an element surrounding the text inside the content-`<div>`... This shouldn't be a problem, because at least there should be a `<p>` element, but sometimes, plugins add text directly to the div, so it causes this issue.

**Comment by pfefferle** [comment] 2018-02-13 12:35
I just saw that you have build your own child-theme and that you simply include the `style.css`, but this is not enough, I splitted the view-port dependent stuff into several stylesheets. You have to include 5 styles in total: https://github.com/pfefferle/ZenPress/blob/master/functions.php#L232

**Comment by mrkrndvs** [comment] 2018-02-13 12:43
What forced me to change was the headless notes rss. This would not be an issue with my main site which is just for 'Articles'.

**Comment by mrkrndvs** [comment] 2018-02-13 12:44
When I get a chance I will also turn off the plugins one by one and try and identify what is causing the issue with the search screen.

**Comment by pfefferle** [comment] 2018-02-13 12:45
what was the problem with the "headless notes rss"?

**Comment by mrkrndvs** [comment] 2018-02-13 12:51
Micro.blog requires 'no titles':

> Part of indie microblogging is getting back to the simplicity of title-less posts. When you’re writing a microblog post in WordPress, just leave the title blank, and if necessary update the post template to not include the title in HTML or the RSS feed.([source](http://help.micro.blog/2018/setting-up-wordpress/))

For some reason it the posts were producing a "No Title" Title, so I tried David's 2016 (which I know does not have headings for notes) and it did worked.

Not sure if that makes sense.

**Comment by pfefferle** [comment] 2018-02-13 12:58
thanks for the hint @mrkrndvs, the latest commit should fix that problem.

**Comment by mrkrndvs** [comment] 2018-02-13 13:26
At present, no to Gutenberg

**Comment by mrkrndvs** [comment] 2018-02-20 11:31
@pfefferle I have had a second go at getting a [child theme](https://github.com/mrkrndvs/ZenChild) developed by @ChrisAldrich working again with no success. I added all the stylesheets, but there is still aspects of the parent theme that are not coming through.

**Comment by mrkrndvs** [comment] 2018-02-20 11:37
Do I need to add Gutenberg for it to work?

**Comment by pfefferle** [comment] 2018-02-20 12:41
No, you do not need Gutenberg... I think I have to release a "Client-Theme skeleton" to test it by myself...

**Comment by pfefferle** [comment] 2018-02-20 12:42
Thanks for the feedback!

**Comment by mrkrndvs** [comment] 2019-03-11 11:59
Updated the theme for [Read Write Respond](https://readwriterespond.com) from [ZenPress](https://collect.readwriterespond.com/zenpress/) to [Autonomie](https://chat.indieweb.org/wordpress/2019-03-09/1552165929626000).
